Add Rollup to project
jamescallumyoung/gif-provider pull request #21
Opened 2020-10-21 20:19 UTC by fernando24164

Hi,

I check #18 issue to add Rollup to the project.

If you think this it is useful for you, I would appreciate you will add hacketoberfest-accepted tag.

Thx!

2020-10-22 09:24 UTC, jamescallumyoung commented
Hi @fernando24164, thanks for the contribution. This project is open-source and has opt-in for hacktoberfest since I'm a fan of the project.

However, contributors should read the CONTRIBUTING guide before contributing. This is good open source etiquette and following the processes defined there helps maintainers manage their projects. It also helps reduce wasted effort. In this case, you didn;t indicate your interest in the issue so we didn;t have a chance to discuss your proposed changes.

That said, I'm happy to approcve your contributing with a few changes.

Could you explain your reasoning for adding Babel and changing the import/export method to `* from` in some cases? It's my understanding that Rollup (using the plugin specified in #18 ) can handle TS without needing Babel.

2020-10-22 09:29 UTC, jamescallumyoung requested changes

2020-10-22 09:29 UTC, jamescallumyoung commented on package.json
> +    "build": "tsc --allowSyntheticDefaultImports",
Can you specify why the `--allowSyntheticDefaultImports` flag is needed here and not in `build:js`

2020-10-22 09:29 UTC, jamescallumyoung commented on package.json
> +    "@babel/preset-typescript": "^7.9.0",
As mentioned in my main comment, please specify why Babel is needed.

2020-10-22 09:29 UTC, jamescallumyoung commented on src/index.ts
> +export * as Gif from './Gif'
Why the `* from` change?

2020-10-22 09:29 UTC, jamescallumyoung commented on src/providers/GiphyGifProvider.ts
> +import giphyApi from "giphy-api";
Why change from `require`?

2020-10-22 09:29 UTC, jamescallumyoung commented on src/providers/index.ts
> +export {TenorGifProvider as TenorGifProvider} from './TenorGifProvider'
Is this needed? Otherwise, please reverse.

2020-10-22 09:29 UTC, jamescallumyoung commented on package.json
> +    "build:js": "npm run build && rollup -c",
This project uses `yarn` not `npm`. Please update to:
```suggestion
    "build:js": "yarn build && rollup -c",
```

2020-10-22 09:29 UTC, jamescallumyoung commented on .babelrc
> +}
```suggestion
}

```

2020-10-22 12:23 UTC, fernando24164 commented
Sorry for not take a look to CONTRIBUTING file. I will update the issue and the PR ASAP.
Thx

2020-10-26 20:36 UTC, fernando24164 reviewed
I added the new changes to get updated with the last changes from master and I have also modified commit message to be properly defined like the rest of the project.
My first solution for resolve #18 was parsing typescript code using babel project. Reading more carefully your proposal typescript plugin resolve everything out of the box without babel.
The only problem I have found it is defined root directory in tsconfig due this plugin needs it to generate the final js file.
Finally, I added [terser](https://github.com/terser/terser) [plugin](https://github.com/TrySound/rollup-plugin-terser) to Rollup to try to compress as much as possible the final js file size.

2021-08-09 09:54 UTC, jamescallumyoung commented
Stale.

2021-08-09 09:54 UTC, closed without merging